# -*- coding: utf-8 -*-
"""MLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k61NxqcL3QfM2wpkKWbBaze07uPhvmo-
"""

import pandas as pd
import numpy as np

bnotes=pd.read_csv('bank_note_data.csv')

bnotes.head()

bnotes.shape

bnotes.describe(include='all')

x= bnotes.drop('Class',axis=1) # axis is droping the coloumn and if it was 0 it will drop the rows
y= bnotes['Class']
print (x.head(2))

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

print(x_train.shape)
print(y_test.shape)

from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier(hidden_layer_sizes=(3,2),max_iter=500,activation='relu')
mlp

mlp.fit(x_train,y_train)
pred=mlp.predict(x_test)
pred

from sklearn.metrics import classification_report,confusion_matrix
confusion_matrix(y_test,pred)

print(classification_report(y_test,pred))